# Generated by GPT-5 on 2026-05-05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("salon", "0004_alter_aidata_options_alter_appointment_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AiTrainingRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Дата запуска")),
                ("model_version", models.CharField(default="", max_length=100, verbose_name="Версия модели")),
                ("threshold", models.DecimalField(decimal_places=2, default=0.5, max_digits=4, verbose_name="Порог классификации")),
                ("n_samples", models.PositiveIntegerField(default=0, verbose_name="Размер выборки")),
                ("n_positive", models.PositiveIntegerField(default=0, verbose_name="Положительный класс (no_show)")),
                ("accuracy", models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name="Accuracy")),
                ("precision", models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name="Precision")),
                ("recall", models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name="Recall")),
                ("f1", models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name="F1")),
                ("tp", models.PositiveIntegerField(default=0, verbose_name="TP")),
                ("fp", models.PositiveIntegerField(default=0, verbose_name="FP")),
                ("tn", models.PositiveIntegerField(default=0, verbose_name="TN")),
                ("fn", models.PositiveIntegerField(default=0, verbose_name="FN")),
                ("notes", models.TextField(blank=True, default="", verbose_name="Примечания")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_training_runs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто запустил",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "verbose_name": "запуск обучения AI",
                "verbose_name_plural": "история обучения AI",
            },
        ),
    ]

